# constants.py

# 상수
ERROR_MESSAGE_INVALID_OPERATOR = "[SYSTEM] Invalid Operator"
ERROR_MESSAGE_INPUT_ERROR = "[SYSTEM] Input Error"
ERROR_MESSAGE_OUT_OF_RANGE = "[SYSTEM] Out Of Range"

EASTER_EGG_CODE_1 = '987654321987654321'
EASTER_EGG_CODE_2 = '7503'
EASTER_EGG_CODE_3 = '1015'

EASTER_EGG_MESSAGE_1 = "[EVENT] \"Hello! This Is Team Yeonhyo Easter Egg!!\""
EASTER_EGG_MESSAGE_2 = "[EVENT] \"안녕! 7503은 사용할 수 없는 숫자야\""
EASTER_EGG_MESSAGE_3 = "[EVENT] 전북대 개교기념일입니다."